all: rats
	g++ -std=c++11 -Wall -lGL -lGLU -lglut bitmap_image.hpp defs.hpp hmm.hpp kmeans.hpp stringsplit.hpp placecell.hpp pathpoint.hpp path.hpp sprite.hpp stringsplit.cpp placefield.hpp spritefamily.hpp rat.hpp glew.c hmm.cpp kmeans.cpp process.hpp placefield.cpp spritefamily.cpp texture.hpp placecell.cpp path.cpp sprite.cpp rat.cpp process.cpp rats.cpp -o rats
